### ISSUE TITLE
Does vcf2ahmm.py work will pool-seq data? How to incorporate a recombination rate map?

### ISSUE THREAD

**Issue by apfuentes** [russcd/Ancestry_HMM#12]
Hi @russcd,

We have pool-seq data (1 pool each = parental spp1, parental spp2, admixed population) and want to use AHMM to estimate the time and size of the introgression pulse in an admixed population.

Two questions:

1. Does the script `vcf2ahmm.py` work for Pool-seq data?  We have a VCF file, and SNPs were called using GATK-genotypecaller
2. How does the script estimate the distance in Morgans between consecutive positions? 

I noticed that by default the script assumes "...A single uniform per basepair, per generation recombination rate. Default: 1e-8...", but it is not clear to me how that information is used in the script to print the respective column in the input file for AHMM.

We have a recombination map for one of the parental species, so I wonder if we should use this information to calculate the distance in Morgans (recombination rate per bp in morgans/bp). I don't see a flag that receives this data, so I guess this should be hard-coded?

Thanks

**Comment by russcd** [comment]
Hi There, 

vcf2ahmm.py is not really appropriate for what you're doing. It is designed for a very simple case, but the data you're describing might be appropriate for AHMM framework. 

I think it's going to take a little discussion, so could you send me an email and I'll be happy to help think about how to do this.
