### ISSUE TITLE
time estimated > tmax

### ISSUE THREAD

**Issue by aguilar-gomez** [russcd/Ancestry_HMM#14]
We ran the following command
`ancestry_hmm -i ahmm_input_puma_parameters2 -s samplefile_Oct7 -a 2 0.79 0.21 -p 0 1000 -0.79 -p 1 -6 -0.21 -tmax 100`

and this was the optimal model
optimum: 
	type	time	proportion
	0	1000	0.79
	0	1000	0.79
	1	6910.14	0.21
	1	6910.14	0.21

How is it possible that the time inferred for pop2 is larger than the tmax? We know the admixture is very recent and should be 1-6 generations ago. Some individuals are F1 of the populations.

**Comment by russcd** [comment]
Hi There! 

Could you try "--tmax" instead of "-tmax"?

**Comment by russcd** [comment]
I'm closing this, but please re-open if this did not solve the problem.
