### ISSUE TITLE
Fail to running Ancestry_HMM v1.0.2

### ISSUE THREAD

**Issue by ghost** [russcd/Ancestry_HMM#15]
Hi @russcd ,
Thank you for providing this tool. 

I encountered some problems when running Ancestry_HMM v1.0.2
I want to estimate the admixture time of admixed population A,  which origins are B and C (both are admixed populations, I assume they are ancestries of populatipn A, and B received an one-pulse introgression from C).

Firstly, I used vcf2ahmm.py to generate ahmm_input_file of B&C , and generate the ploidy.txt of A.
ahmm_input_file of B&C was successfully output, but ploidy.txt of A was not.

My command line for creating ploidy.txt  is : python3 vcf2ahmm.py -v A_22chr.vcf -s A-sample2pop-map-.txt -o A-ploidy 
(A-sample2pop-map-.txt with two columns are sample A1 admixed)

So I created another tab-delimited ploidy.txt file to run the program.

My command line like this :
ancestry_hmm -i B_C_ahmm -s A-sample-file.txt -a 2 0.7 0.3 -p 0 410 0.7 -p 1 400 0.3 (B as 0, C as 1)

reading command line				9 ms
reading sample ids and ploidy			82 ms
creating states matrix				6 ms
reading data and creating emissions matrices	zsh: segmentation fault   ancestry_hmm -i B_C_ahmm -s  -a 2 0.7 

But the program stopped here. I don’t know which step got wrong.

And my another question is that, if I want to run Ancestry_HMM, the input file (–s [sample_file]) that program read only accepts ploidy.txt vcf2ahmm.py generate ?

Thanks,
Wei-Chen

**Comment by russcd** [comment]
Hi Wei-Chen, 

The program typically dies at this step when there's a formatting issue in the input file. Could you send me an example that reproduces this result so I can try to figure out what's going on? 

Thanks, 

Russ

**Comment by ghost** [comment]
Hi Russ,

The following are the formats of input files generated by vcf2ahmm.py  

1	3681681	18	22	32	8	0.04681681
1	4066680	35	5	30	10	0.00384999
1	4342604	16	24	27	13	0.00275924
1	4933235	34	6	22	18	0.0059063100000000006
1	5093741	22	18	33	7	0.00160506
1	5612956	32	8	23	17	0.00519215
1	6380287	36	4	31	9	0.00767331

TW-HA-000063-1-01_TW-HA-000063-1-01	2
TW-HA-000196-1-01_TW-HA-000196-1-01	2


Is the formatting issue that there are not read counts of allele A in sample 1 in my input file ?

My A and B&C populations are separate vcf files, should I combine two vcf files by using their same SNPs first and use combined vcf file to generate the ahmm input file ?


Thanks,

Wei-Chen

**Comment by russcd** [comment]
Hi Wei-Chen, 

You are correct that all samples (reference and admixed) must be in a single vcf file for that script to work correctly.
