### ISSUE TITLE
Getting -nan values in posterior files

### ISSUE THREAD

**Issue by Madshartmann1** [russcd/Ancestry_HMM#17]
When running my data, that originates as a vcf file, through the program i get a large amount of -nan values in my resulting .posterior files. I can se from the run status that it seems to stem from "Computing forward probabilities lnl: -nan". 

This only seems to occur when i try to test a lot of samples at once (not a problem with 20 samples but is is with 200) 

Any ideas on what is causing the model to behave like this ?

**Comment by russcd** [comment]
Hi there. 

It is likely that the program has an uncaught underflow somewhere. Can you send me an example file that reproduces this problem so I can debug it?

Thanks. 

Russ

**Comment by Madshartmann1** [comment]
Hi again 

I have added 4 example files for you in the repo below. 
The bigger fileset produces the "Computing forward probabilities lnl: -nan" in the run status, but both the bigger and smaller fileset result in -nan values in the posterior files. 

As the dataset is from a source without pulse info the command used is as follows 
ancestry_hmm -i filname.panel -s filename.ploidy -a  4 0.15 0.30 0.5 0.05 -p 0 1 0.25 -p 1 1 0.25 -p 2 1 0.25 -p 3 1 0.25


You can find the files here:
https://github.com/Madshartmann1/AHMM_fileshare 

Hope you find something, and thanks in advance
Mads
