### ISSUE TITLE
Ploidy level of samples

### ISSUE THREAD

**Issue by oushujun** [russcd/Ancestry_HMM#2]
Hello,

I have a simple question: My focal species is a diploid. If I generate the input file using haploid genotypes, should I specify samples as haploid or diploid?

Thanks,
Shujun

**Comment by russcd** [comment]
HI Shujun, 

If your genotypes are haploid, you'll need to specify samples as haploid for the program to run correctly. 

However, it might not be a good choice to force diploid samples to have haploid genotypes. If each genotype is sampled at random from each of the two chromosomes, this might cause unreasonably high transition rates between ancestry types since the local relationship among alleles will be lost. 

Best, 

Russ

**Comment by oushujun** [comment]
Hi Russ,

Thanks for your quick response. Sorry I didn't tell that my species is a selfing plant (rice) with an inbreeding coefficient ~0.8, so all heterozygous SNP calls were removed to control data quality, resulting in the possibility of retaining only the haploid genotype. Giving the long run of homozygosity (could be slightly biased), would it be possible to retrieve ancient (e.g., 5,000-10,000 generations ago) admixture pulses?

Thanks again!

Shujun

**Comment by russcd** [comment]
I see. Yes, for very strongly inbred samples, ploidy = 1 and haploid genotypes is almost certainly the right choice. 

With respect to timing ancient admixture pulses pulses, the performance depends on how genetically differentiated the ancestral populations are and how much ancestral linkage disequilibrium there is.

**Comment by oushujun** [comment]
Thanks for your confirmation. Fst of these populations is quite large (>0.2), as for ancestral LD, I don't have a clue but I definitely would try it out. 

For the uncertainty of the estimation, is it recommended to use bootstrap and obtain the mean or distribution of the estimated pulse time? If so, how many reps are recommended?

**Comment by russcd** [comment]
That level of Fst is in the range of data we have used successfully to date ancient admixture events. So, this might work for you. 

I generally use a minimum of 100 bootstraps to get my confidence intervals.

**Comment by oushujun** [comment]
Thanks!

Shujun
