### ISSUE TITLE
The effect of bottleneck events to the estimation of pulse time

### ISSUE THREAD

**Issue by oushujun** [russcd/Ancestry_HMM#3]
Dear Russ,

I read the discussion about effective population size (Ne) in the Corbett-Detig and Nielsen (2017) paper, but still not sure about if the assumption underlying is a constant Ne throughout the coalescent time. If yes, then how changing of Ne in the past (i.e., a bottleneck) may affect the estimation of pulse time? In the purpose of making sense of the current method framework, what Ne should I provide to `ancestry_hmm` giving the knowledge of historical Ne?

Thanks,
Shujun

**Comment by russcd** [comment]
Hi Shujun, 

If the bottleneck was severe such that many loci around the genome coalesced, the program will likely underestimate the admixture time. If the bottleneck was relatively weak, the effect should be fairly minor. 

Best, 

Russ

**Comment by oushujun** [comment]
Hi Russ,

Yes, the bottleneck was very intense. Pre-bottleneck Ne is ~1e6 (>10,000 gen), the bottleneck Ne is ~1e3 (10,000 gen), and post-bottleneck Ne recovers to ~1e5 (100 gen). Most likely population admixture occurs after the bottleneck (100 - 10,000 gen), so at the time of admixture, Ne was like 1e3 to 1e4. With this information, and knowing the pulse time will be underestimated, what Ne fits better to `ancestry_hmm`?

Thanks,
Shujun

**Comment by russcd** [comment]
This is a very tricky question. Definitely not something we have worked with before. All I can really suggest is that you try it both ways and see what happens.

**Comment by oushujun** [comment]
Advise taken. Thanks!

Shujun
