### ISSUE TITLE
Determining and specifying the model

### ISSUE THREAD

**Issue by oushujun** [russcd/Ancestry_HMM#4]
Hi Russ,

This thread includes two parts.

**Part 1: detemining the introgression model**

So I have an admixed population A, which geonmic origin is possibily B and C. From admixture analysis, A consists of 55% B, 40% C, and 5% others. I have distinct and nonadmixed samples for both B and C, with admixture compositions account for >99% of each sample's genome. Schematically, A could be derived from the unobserved ancestor A', which probably went distinct already if this is the case, and A' received two-pulse introgressions from B and C. For the other model, either B or C received an one-pulse introgression from C or B, making the current A. I am not sure which model fits better for my data. Any suggestions?

Admixture of my samples:
![image](https://user-images.githubusercontent.com/5996084/46312981-afcbc980-c594-11e8-8de9-38500708cac2.png)

Models from Medina et al. (2018):
![image](https://user-images.githubusercontent.com/5996084/46311767-3a122e80-c591-11e8-9050-d9ed9b2b6ec4.png)

![image](https://user-images.githubusercontent.com/5996084/46311697-07683600-c591-11e8-8c7c-be1442abf915.png)

**Part 2: specifying the model**

I find myself confused about specifying a model too. Here I will use a single-pulse two-ancestral population model. More paticularily, let's specify pop C received an introgression pulse from B, making the admixed pop A.  

To specify this model, for columns in the `-i <input_file>`, 
>1. Chromosome
>2. Position in basepairs
>3. Allele counts of allele A in reference panel 0
>4. Allele counts of allele a in reference panel 0
>5. Allele counts of allele A in reference panel 1
>6. Allele counts of allele a in reference panel 1
>7. Distance in Morgans
>8. Read counts of allele A in sample 1
>9. Read counts of allele a in sample 1
>10. Read counts of allele A in sample 2
>11. Read counts of allele a in sample 2
>...

**Question 1**: For  columns 3-6, do I only need allele counts for B and C or should I also add two more columns for A?

**Question 2**: My interest is in the local ancestry of A. For columns 8-end, should I put only A samples or all A, B, and C samples?

**Question 3**: For the `-s <sample_file>`, should I put samples in A, B, and C in the same order of `-i <input_file>` or only put A? From the example, I saw only 4 samples in the sample list, but in the panel file, the two reference population has 46 samples each (assuming all diploids).

**Question 4**: To specify this **one-pulse** model, should I use `-a 3 0.55 0.4 0.05` of `-a 2 0.55 0.4` (the two numbers are not added to 1)?

Greatly appreciated for all your helps!

Best,
Shujun

**Comment by russcd** [comment]
For part 1: The program assumes all ancestral populations that contributed to the admixed population were sampled. Since A' is not included in your dataset this might be a problem. 

Question 1. A would not be specified here since it is the admixed population. Instead, the allele counts in columns 8-n should reflect each sample of the admixed population, A. 

Question 2. 8-end should contain samples from the admixed population. 

Question 3. You need only specify A in the sample file and yes, the order must be same as the order of columns across the file. 

Question 4. If there are three ancestral populations, this is inherently at least a two pulse model. Since you do not have representatives of A', you would probably do something like the second except "-a 0.575 0.425" or something like that.

**Comment by oushujun** [comment]
Dear Russ,

Thank you for your insights. For more context, both A and C are "wild" populations while B is a domesticated population. For simplicity, I think I will treat C as the unadmixed ancestral population, then A is the result of introgression from B to C. It's also possible that A is a feral population that escaped from domesticated B (de-domestication) and receives introgressions from C, but this is less likely because B is selfed while A,C has much lower inbreeding (*F* ~0.6), which parsimoniously are more likely to be pollen receivers.

Many thanks for your clarification of the input format. I have modified your code for infile preprepartion using VCF and a bunch of other information specified by other files. This version can support up to 3 reference populations.

[vcf2ahmm_4pop.pl.zip](https://github.com/russcd/Ancestry_HMM/files/2438732/vcf2ahmm_4pop.pl.zip)

I think it would be helpful for other users so I upload it here. For the detailed usage, please type `perl vcf2ahmm_4pop.pl -h`.

Best,
Shujun
