### ISSUE TITLE
Estimation strategy

### ISSUE THREAD

**Issue by oushujun** [russcd/Ancestry_HMM#8]
Hi Russ,

For joint estimation of both time and pulse size, I got relative stable estimations for the pulse size, which standard deviation ranges from 1-5% of the bootstrap mean. However, the estimated time could vary up to 12% and usually not normally distributed. Based on these observations, can I first jointly estimate both time and pulse size, then fix the pulse size as the bootstrap mean in the second estimation and only estimate pulse times for more accurate results?

Another question:

When I plot out the estimated time of a single pulse (y) for a reference, the violin plot shows a bimodel distribution as follows. Is this mean this reference is potentially contributed more than one pulse (i.e., 2)?
![image](https://user-images.githubusercontent.com/5996084/47392691-4e0e0380-d6eb-11e8-9860-58bab09b0674.png)

Thanks!
Shujun

**Comment by russcd** [comment]
1. Time estimates vary by about 12%. This is not too unusual especially for relatively old pulses. 

2. But clearly the variance in your plot is much larger, so something else is going on. I am not sure if that's consistent with a second pulse or not. A guess is that there's a lot of allele frequency change between  one of your reference populations and the true donor population. This can cause strange patterns like that, in which case probably the true admixture time is closer to the younger mode.

**Comment by oushujun** [comment]
Thanks for your insights!

For the first question, I used the initial pulse size estimate for the second-time estimation, which is to fix the pulse sizes and onle estimate pulse times - with fewer parameters the calculations were definitely faster and with less variation.

For Q2, I added one more pulse based on the observation of the one-pulse model (the figure above), and the estimated pulse times looks more like normal distributions (although with long tails). See below:
![image](https://user-images.githubusercontent.com/5996084/47472964-98bc7800-d7de-11e8-9fe9-b33275c0e818.png)

Note that if I add one more pulse on the two-pulse model, the additional pulse will be estimated very ancient (12,000 - 15,000 generations ago), does that mean that the 3rd pulse are shared between the admixed population and the donor population that are derived from their common ancestor (i.e., not introgressed)?

Thanks,
Shujun

**Comment by russcd** [comment]
In simulations we've done, very ancient pulses are unreliable and tend to contribute a very small proportion of the total ancestry. If it also contributes a lot of the ancestry, my guess is either that you have an ancient shared ancestry component, or that there is significant allele frequency change between your reference population and the true donor population. 

I have never tried the two-step estimation procedure you are describing. I am not sure that's the way to go with this. When estimating the first pulse when there are really two pulses, the time will be impacted by ancestry from each. If you then lock that in and estimate the second pulse, it should bias your time estimates. I'd defintely prefer to jointly estimate the two pulse times if feasible.

**Comment by oushujun** [comment]
Hi Russ,

Thank you for your insights! I agree that fixing one pulse and estimate another is likely a biased procedure. For the two-step estimation procedure, I separate the estimation between pulse sizes and pulse times with fixed pulse numbers (ie, 2), but not separating different pulses. Step 1 is a one-time estimation for both time and size. Step 2 is to fix the estimated pulse size and reestimate pulse time with bootstrapping. This is based on the observation that variations in estimated pulse size is usually not as large as the time estimation. In this way, I can perform the pulse time bootstrapping much more efficiently by reducing parameter numbers for multiple pulse models. For a quite extreme example, I specified a 4-pulse model to jointly estimate pulse time and size (7 parameters), but it has been almost a month and not producing an initial estimation yet, let along bootstrapping.

Thanks again!

Shujun
