### ISSUE TITLE
Feature request: output estimations after each bootstrap

### ISSUE THREAD

**Issue by oushujun** [russcd/Ancestry_HMM#9]
Hi Russ,

I think this feature will be nice, that the bootstrap estimation will be printed after each bootstrap, but not only printed after all bootstraps finished. Sometimes I specified unrealistically large bootstrap replications that will take a very long time, but at the same time, I want to evaluate the results before all replications were done.

Thanks,
Shujun

**Comment by russcd** [comment]
Hi Shujun, 

You can get this information from the standard error filestream which will print each optimum as it is reached. 

Best, 

Russ

**Comment by oushujun** [comment]
Hi Russ,

Thanks for your help. I can get some information from the standard error filestream, but not sure how to interpret information in the third column. For example:
>
>                                CONTRACTION ACCEPTED
>restart: 240    9.68575e-06
                1e+06   1       1
                1203.94 0       0.552669
                99999.9 0       0.298455
                87.777  0       1

This is a two-reference introgression model with fixed Pop1 and three introgression pulses from Pop0. The three pulse sizes and times are jointly estimated. Population 0 has three values: 0.552669, 0.298455, and 1, but added up > 1. Is that a way to get the inference of pulse size for bootstraps from the filestream?

Thanks again!
Shujun

**Comment by russcd** [comment]
I see. What's going on here is that this is reporting the proportion of the remaining unaccounted ancestry (which is how this is actually recorded within the program). 

So, for pulses 2-4, the first has 0.55 
The second has 0.29 of the remaining 0.45, so approximately 0.13
The final pulse has all of the remaining ancestry of type 0. 

So, if you search through the standard error for the optimum you can easily find those models and update them as I am describing. 

I will also try to add this feature when I have a moment next week.

**Comment by oushujun** [comment]
Got it, thanks for the explanation!

Shujun
